[workspace]
members = ["crates/*"]
default-members = ["crates/cargo-optic"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/connortsui20/optic"

[workspace.dependencies]
anstyle = "1.0.13"
base64 = "0.22.1"
blake3 = "1.8.2"
cargo-ir = { path = "crates/cargo-ir", version = "0.0.1" }
cargo_metadata = "0.23.1"
clap = { version = "4.5.48", features = ["derive"] }
fs2 = "0.4.3"
libc = "0.2.189"
proc-macro2 = { version = "1.0.101", features = ["span-locations"] }
rusqlite = { version = "0.40.2", features = ["bundled"] }
rustc-demangle = "0.1.26"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_yaml = "0.9.34"
syn = { version = "3.0.3", features = ["full", "visit"] }
tempfile = "3.27.0"
thiserror = "2.0.17"
toml = "1.1.4"
two-face = { version = "0.5.1", default-features = false, features = ["syntect-fancy"] }
uuid = { version = "1.18.1", features = ["serde", "v4", "v7"] }
walkdir = "2.5.0"
zstd = { version = "0.13.3", default-features = false }

[workspace.lints.clippy]
