[package]
name = "optic_records"
version = "0.0.1"
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
snafu.workspace = true
uuid.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
