[package]
name = "cargo-optic-evidence"
version = "0.0.1"
publish = false
edition.workspace = true
license.workspace = true

[lib]
name = "optic_evidence"

[dependencies]
cargo-optic-records.workspace = true
cargo-optic-store.workspace = true
snafu.workspace = true

[dev-dependencies]
tempfile.workspace = true
