[package]
name = "cargo-ir"
version = "0.0.1"
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rustc-demangle.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
walkdir.workspace = true

[lints]
workspace = true
