[package]
name = "optic"
version = "0.0.1"
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
optic_capture.workspace = true
optic_compiler.workspace = true
optic_records.workspace = true
optic_store.workspace = true
snafu.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
