[package]
name = "cargo-optic"
description = "Capture concrete Rust instances and inspect their source and optimized LLVM"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true
exclude = ["tests/**"]

[dependencies]
cargo-optic-api.workspace = true
clap.workspace = true
snafu.workspace = true
time.workspace = true

[dev-dependencies]
cargo-optic-test-support = { path = "../cargo-optic-test-support" }
tempfile.workspace = true
