[package]
name = "cargo-optic-capture"
version = "0.0.1"
publish = false
edition.workspace = true
license.workspace = true

[lib]
name = "optic_capture"

[dependencies]
cargo-optic-compiler.workspace = true
cargo-optic-records.workspace = true
cargo-optic-store.workspace = true
snafu.workspace = true
