[package]
name = "cargo-optic-capture"
description = "Capture reuse and publication orchestration for Cargo Optic"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true

[lib]
name = "optic_capture"

[dependencies]
cargo-optic-compiler.workspace = true
cargo-optic-records.workspace = true
cargo-optic-store.workspace = true
snafu.workspace = true
